production:
  adapter: postgresql
  database: signalchains_production
  username: deploy
  password: 705YR8jptajUcOb2KQnl
  host: localhost
  encoding: UTF-8

staging:
  adapter: postgresql
  database: signalchains_production
  username: deploy
  password: 705YR8jptajUcOb2KQnl
  host: localhost
  encoding: UTF-8