embed_assets: datauri
javascript_compressor: closure

javascripts:
  default:
    - "public/javascripts/jquery-ui.custom.min.js"
    - public/javascripts/plugins/jquery.validate.js
    - public/javascripts/jrails.js
    - public/javascripts/plugins/jquery.form.js
    - public/javascripts/plugins/jquery.scrollTo.js
    - public/javascripts/plugins/jquery.localscroll.js
    - public/javascripts/plugins/jquery.uniform.js
    - public/fancybox/fancybox.js
    - public/javascripts/plugins/jquery.cuteTime.js
    - public/javascripts/application.js

stylesheets:
  default:
    - public/stylesheets/uniform.default.css
    - public/stylesheets/application.css
    - public/stylesheets/fonts.css    
    - public/stylesheets/style.css
    - public/fancybox/fancybox.css
    - "public/stylesheets/custom-theme/custom.css"
    - public/stylesheets/home.css
    - public/stylesheets/events.css
    - public/stylesheets/chains.css
    - public/stylesheets/audioplayer.css
    - public/stylesheets/user.css