--- 
- name: staging-1
  created_at: 2009-12-16 09:22:19 -06:00
  environment_class: Staging
  id: 128266
  ip: 67.23.42.159
  password: staging-1a0YjakN
- name: staging-2
  created_at: 2009-12-16T09:25:33-06:00
  environment_class: Staging
  id: 128267
  ip: 67.23.42.163
  password: staging-2tB0hEWJ
